scope: postgres_cluster
namespace: /service/
name: node3

restapi:
  listen: 192.168.31.173:8008
  connect_address: 192.168.31.173:8008

etcd3:
  hosts: ["192.168.31.171:2379", "192.168.31.172:2379", "192.168.31.173:2379"]

bootstrap:
  method: initdb
  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  pg_hba:
  - host replication replicator 192.168.31.0/24 md5
  - host all all 192.168.31.0/24 md5
  - host all all 0.0.0.0/0 md5
  - host replication replicator 192.168.31.0/24 scram-sha-256
  - host postgres postgres 192.168.31.0/24 md5

  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: logical
        hot_standby: "on"
        wal_keep_size: 128MB
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: '/bin/true'
        shared_preload_libraries: 'pg_stat_statements'
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all

postgresql:
  listen: 192.168.31.173,127.0.0.1
  connect_address: 192.168.31.173:5432
  data_dir: /var/lib/postgresql/17/main
  bin_dir: /usr/lib/postgresql/17/bin
  authentication:
    replication:
      username: replicator
      password: replication_pass
    superuser:
      username: postgres
      password: postgres_pass
  parameters:
    unix_socket_directories: '/var/run/postgresql'

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: true
  nosync: false
